version: 0.2

env:
  variables:
     BUILD_FOLDER: "dist"
batch:
  fast-fail: true

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo Installing dependencies...
      - npm ci
  build:
    commands:
      - echo Running build for Vite React app...
      - npm run build

artifacts:
  files:
     - '**/*'
  discard-paths: no
  base-directory: $BUILD_FOLDER
